# Publish this application to bluemix using ansible
---
- name: Publish the app to AWS EC2
  hosts: localhost
  connection: local
  vars:
    app_name: "{{ lookup('env','APP_NAME') }}"
    s3_bucket: "{{ lookup('env', 'S3_BUCKET') | default(app_name,true) }}"
    region: "{{ lookup('env', 'AWS_DEFAULT_REGION') | default('us-west-2', true) }}"
    cluster_name: "{{ lookup('env', 'CLUSTER_NAME') | default('new_cluster', true) }}"

  tasks:
    # ------------------------------------------------------------
    # Create an ECS Cluster
    # ---
    # http://docs.ansible.com/ansible/ecs_service_module.html
    - name: Wait for register
      ecs_cluster:
        name: "{{ cluster_name }}"
        state: present
        region: "{{ region }}"
      register: result

    - debug: msg="{{ result }}"
